filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/messages
  fields:
    type: syslog
  fields_under_root: true
output.logstash:
  hosts: ["logstash01:5044","logstash02:5044"]
  loadbalance: true

