filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/messages
  fields:
    type: syslog
  fields_under_root: true
output.logstash:
  hosts: ["logstash01:5044","logstash02:5044"]
  loadbalance: true
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ["logstash01:9200","logstash02:9200"]
  compression_level: 0
